### ISSUE TITLE
token problem

### ISSUE THREAD

**Issue by ccaramel** [Leighm0/enphase_gateway#2]
Hi,
that seems pretty promising.
I still have an error in lua:

(): No Auth Token yet, not continuing.

any input to solve it?
regards.

**Comment by Leighm0** [comment]
Hi, I need more details on your error and what your setup is, and have you configured the driver properly. No Auth Token means it's not getting a token from the enphase API, have you entered in your enphase credentials in the properties?

**Comment by ccaramel** [comment]
ty for your answer.
I tried to configure driver both ways, auto and manual.
Credentials are also entered.
I have feedback from gateway indicating its SN, part number and software version (7.6.175).

**Comment by Leighm0** [comment]
Test that you can login successfully and obtain a token on the enphase site below using the credentials you entered in the driver:
https://entrez.enphaseenergy.com/login - Select "For commissioned gateway" once logged in, enter your System name in the first box (can be found in enlighten webpage below - will be in the top left next to the "Full System" drop down box), and then select your Gateway, then hit "Create access token" and confirm it gives you one...

Also confirm the same credentials can see your system on this site:
https://enlighten.enphaseenergy.com/login

Let me know how that goes and if you get any errors from their sites.

**Comment by ccaramel** [comment]
Hi,
I succeded to have a token, but that doesnt solve anything.
Anyway, that seems to be common to others HAS that use envoy integration since D7.6.175 release.
Here is a topic on emphase community:
https://support.enphase.com/s/question/0D53m00008pRVlLCAW/instructions-to-get-access-token
Is there a way to enter access token within the driver you made?
Regards.

**Comment by Leighm0** [comment]
yes, i am aware the token integration - it is in the driver and works for other users, only yours has not worked so far.

You can manually add the token in my driver using the Lua window in Composer pro and do:

gAuthToken = "[your token without spaces]"

and "execute" it, and then it should use your token for api access.

**Comment by ccaramel** [comment]
That worked perfectly!! Thank you!

**Comment by Leighm0** [comment]
awesome, glad you got it working.

**Comment by RollyandSam** [comment]
Hi,
Just installed this on my C4 setup. Initially the same problem as above, it seemed it isn't getting the token response from Enphase automatically using the username and password. Generating and pasting the generated token into the lua window as mentioned above brought it to life, and is now working.

this link you mentioned above:
https://entrez.enphaseenergy.com/login
just fails. To get to that page I have to go via:
https://entrez.enphaseenergy.com/login_main_page

Does the TokenURI variable in your code need to be updated to:
https://entrez.enphaseenergy.com/entrez_tokens
This is the address showing when I go directly to generate a token.

**Comment by Leighm0** [comment]
> Hi, Just installed this on my C4 setup. Initially the same problem as above, it seemed it isn't getting the token response from Enphase automatically using the username and password. Generating and pasting the generated token into the lua window as mentioned above brought it to life, and is now working.
> 
> this link you mentioned above: https://entrez.enphaseenergy.com/login just fails. To get to that page I have to go via: https://entrez.enphaseenergy.com/login_main_page
> 
> Does the TokenURI variable in your code need to be updated to: https://entrez.enphaseenergy.com/entrez_tokens This is the address showing when I go directly to generate a token.

Hi,

I will look into it more, however the URL's I am using are correct for their use-case, which is script-based token retrieval and not user-based (through a Web UI).

If you look at the official documentation here: 
https://enphase.com/download/accessing-iq-gateway-local-apis-or-local-ui-token-based-authentication
Check Pages 5 and 6 where they discuss the methods to get tokens and include an example Shell/Python scripts.

While the URL's you mention for end users to obtain token themselves through a Web UI are correct, the URL's my driver use are the correct ones for a script-based token retrieval as shown on Page 5/6.

**Comment by RollyandSam** [comment]
Ok, put the driver into debug mode, executed lua code to see the variable outputs.
Forced the driver to get a token, which it did, verified this as correct, along with User, Password, EnvoySerial - all values good.

Then fails with the following error:
URL response callback error: 	driver.lua:433: attempt to index field 'enpower' (a nil value)	https://xxx.xxx.xxx.xxx/home.json

Seems that the grid_status value is not getting filled, thus nil value, and the next line attempts to access a nil field.

I have noticed in the Enphase app and web interface it seems to take around 5 seconds for the On Grid status to populate. Maybe the return via the driver is occurring before this field is populated, thus making this field a nil value.

**Comment by Leighm0** [comment]
> Ok, put the driver into debug mode, executed lua code to see the variable outputs. Forced the driver to get a token, which it did, verified this as correct, along with User, Password, EnvoySerial - all values good.
> 
> Then fails with the following error: URL response callback error: driver.lua:433: attempt to index field 'enpower' (a nil value) https://xxx.xxx.xxx.xxx/home.json
> 
> Seems that the grid_status value is not getting filled, thus nil value, and the next line attempts to access a nil field.
> 
> I have noticed in the Enphase app and web interface it seems to take around 5 seconds for the On Grid status to populate. Maybe the return via the driver is occurring before this field is populated, thus making this field a nil value.

Awesome, thanks for debugging this - does your home.json contain the enpower field at all? I am wondering if maybe some units do not have this, in which case I can work around it with some checks to see if it is nil, etc.

I'm uploading a new version with a check to see if "enpower" is available, skipping it if the value is nil/not present.

**Comment by RollyandSam** [comment]
HI,
just checked what is return in my home.json and there is no enpower field. All that is returned are the Enphase times, Network parameters, tariff setup, and wireless connection details.

Just looked into some of the returns from my system. Firmware version is D8.2.127. Ran a request using the "production.json", but it requires the login authorisation first to get the data, but it then returns data fine. Looking at the code it seems you are differentiating between firmware versions for authorisation, and this is also differentiating url readings.
As I said the production.json returned details fine, and the '/ivp/meters/reading' also returned data.
I have noticed the data showing in my C4 display is noticably different to that from the actual enphase app.

I believe you can still run the production.json request to versions above 7, but they need the authorisation.

I also have batteries, so a 'storage' field is also available.

**Comment by Leighm0** [comment]
> HI, just checked what is return in my home.json and there is no enpower field. All that is returned are the Enphase times, Network parameters, tariff setup, and wireless connection details.
> 
> Just looked into some of the returns from my system. Firmware version is D8.2.127. Ran a request using the "production.json", but it requires the login authorisation first to get the data, but it then returns data fine. Looking at the code it seems you are differentiating between firmware versions for authorisation, and this is also differentiating url readings. As I said the production.json returned details fine, and the '/ivp/meters/reading' also returned data. I have noticed the data showing in my C4 display is noticably different to that from the actual enphase app.
> 
> I believe you can still run the production.json request to versions above 7, but they need the authorisation.
> 
> I also have batteries, so a 'storage' field is also available.

As per the above official API documentation I posted - Enphase prefer that we utilise the '/ivp/meters/readings' URL for gathering data and I believe the 'production.json' will be phased out eventually. Envoy firmware below v7 I believe did not have the '/ivp/meters/readings' URL (I know this as I was on v4 when I started writing this driver and working with a friend who was on v8 sparked me to contact Enphase to upgrade my Envoy firmware), so I reverted to using the old location for obtaining data for those older Envoy's. If you wish to use the production.json, the driver is open source for a reason, copy the code make your own modifications - compile it into a c4z and use it in C4, but I won't be changing it for my driver.

**Comment by Leighm0** [comment]
> I have noticed the data showing in my C4 display is noticably different to that from the actual enphase app.

Make sure you are comparing "Live Status" data in Enphase App rather than the main data shown on the screen when you first open Enphase (which is accumulated stats from up to 15 minutes ago)

**Comment by Leighm0** [comment]
I have made changes to the Auth Flow, so hopefully this fixes sessions and token obtaining for good.
